name: thecognitivelab
region: nyc
domains:
  - domain: thecognitivelab.ai
    type: PRIMARY
static_sites:
  - name: site
    github:
      repo: thecognitivelab/site
      branch: main
      deploy_on_push: true
    output_dir: /
    routes:
      - path: /
